# FILE: start_chroma.yaml
services:
  # ChromaDB for Vector Storage
  chroma:
    image: chromadb/chroma
    container_name: sentient-chroma-selfhost
    ports:
      - "8002:8000" # Expose Chroma's port 8000 on host port 8002
    volumes:
      - chroma_data:/chroma/.chroma/index
    networks:
      - sentient_network

  # NEW: ChromaDB Admin UI
  chromadb-admin:
    image: fengzhichao/chromadb-admin:latest
    container_name: sentient-chroma-admin-ui
    ports:
      - "3001:3001" # Expose the UI on host port 3001
    depends_on:
      - chroma # Ensures ChromaDB starts first
    restart: unless-stopped
    networks:
      - sentient_network

volumes:
  chroma_data:

networks:
  sentient_network:
    driver: bridge