name: Deploy Frontend to Staging

on:
    push:
        branches:
            - staging
        paths:
            - "src/client/**"
            - ".github/workflows/deploy-stag-frontend.yaml"

jobs:
    deploy:
        name: Deploy Frontend to Staging VM
        runs-on: ubuntu-latest
        steps:
            - name: Deploy over SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.STAG_CLIENT_VM_HOST }}
                  username: ${{ secrets.STAG_CLIENT_VM_USER }}
                  key: ${{ secrets.STAG_CLIENT_VM_SSH_PRIVATE_KEY }}
                  script: |
                      set -e
                      cd ~/sentient
                      git pull origin staging
                      cd src/client
                      echo "Building and deploying the frontend..."
                      docker compose down
                      docker compose up --build -d
                      echo "Cleaning up old Docker images..."
                      docker image prune -f
